server {
    listen 80;

    # Acceso al Frontend
    location / {
        proxy_pass http://frontend:8080;
    }

    # Proxy para la Auth API
    location /api/auth/ {
        proxy_pass http://auth-api:8000/;
    }

    # Proxy para TODOs API
    location /api/todos/ {
        proxy_pass http://todos-api:8082/;
    }
}